name: Windows-build

on: [push]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64

    - name: Install CMake
      uses: ssrobins/install-cmake@v1
      with:
        version: 4.0.3

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 17 2022" -T ClangCL -A x64

    - name: Build
      run: cmake --build build