name: Windows-build

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build