name: Windows-build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build