name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

env:
  TWINE_USERNAME: mikados
  TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build manylinux python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64
      with:
        python-versions: 'cp310-cp310'
        build-requirements: 'cython numpy'   
    - name: Build a source distribution
      run: >-
        python3 -m
        build
        --sdist
        --outdir dist/
    - name: Publish wheels to PyPi
      run: |
        twine upload dist/*-manylinux*.whl
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
    