name: Ubuntu-build and 

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ./simulatorTest
